---
acc_cluster:
  - Name: lenet5
  - DMA:
    - Name: dma
      BufferSize: 128
      MaxReq: 4
      PIOMaster: LocalBus
      Type: NonCoherent
      InterruptNum: 95
  - Accelerator:
    - Name: top
      IrPath: benchmarks/lenet5/naive/hw/top.ll
      ConfigPath: benchmarks/lenet5/naive/hw/top.ini
      PIOSize: 9
      PIOMaster: LocalBus
      LocalSlaves: LocalBus
      Debug: False
  - Accelerator:
    - Name: conv0
      IrPath: benchmarks/lenet5/naive/hw/conv0.ll
      ConfigPath: benchmarks/lenet5/naive/hw/conv0.ini
      Debug: False
      PIOSize: 1
      PIOMaster: LocalBus
      Debug: False
    - Var:
      - Name: Conv0Input
        Type: SPM
        Size: 4096
        Ports: 150
    - Var:
      - Name: Conv0Weights
        Type: SPM
        Size: 600
        Ports: 150
    - Var:
      - Name: Conv0Output
        Type: SPM
        Size: 18816
        Ports: 6
    - Var:
      - Name: Conv0LUT
        Type: SPM
        Size: 4
        Ports: 6
  - Accelerator:
    - Name: pool0
      IrPath: benchmarks/lenet5/naive/hw/pool0.ll
      ConfigPath: benchmarks/lenet5/naive/hw/pool0.ini
      Debug: False
      PIOSize: 1
      PIOMaster: LocalBus
    - Var:
      - Name: pool0Input
        Type: SPM
        Size: 18816
        Ports: 24
    - Var:
      - Name: pool0Output
        Type: SPM
        Size: 4704
        Ports: 24
  - Accelerator:
    - Name: conv1
      IrPath: benchmarks/lenet5/naive/hw/conv1.ll
      ConfigPath: benchmarks/lenet5/naive/hw/conv1.ini
      Debug: False
      PIOSize: 1
      PIOMaster: LocalBus
      Debug: False
    - Var:
      - Name: Conv1Input
        Type: SPM
        Size: 4704
        Ports: 150
    - Var:
      - Name: Conv1Weights
        Type: SPM
        Size: 9600
        Ports: 150
    - Var:
      - Name: Conv1Output
        Type: SPM
        Size: 6400
        Ports: 16
    - Var:
      - Name: Conv1LUT
        Type: SPM
        Size: 4
        Ports: 16
  - Accelerator:
    - Name: pool1
      IrPath: benchmarks/lenet5/naive/hw/pool1.ll
      ConfigPath: benchmarks/lenet5/naive/hw/pool1.ini
      Debug: False
      PIOSize: 1
      PIOMaster: LocalBus
    - Var:
      - Name: pool1Input
        Type: SPM
        Size: 6400
        Ports: 64
    - Var:
      - Name: pool1Output
        Type: SPM
        Size: 1600
        Ports: 64
  - Accelerator:
    - Name: fc0
      IrPath: benchmarks/lenet5/naive/hw/fc0.ll
      ConfigPath: benchmarks/lenet5/naive/hw/fc0.ini
      Debug: False
      PIOSize: 1
      PIOMaster: LocalBus
      Debug: False
    - Var:
      - Name: fc0Input
        Type: SPM
        Size: 1600
        Ports: 80
    - Var:
      - Name: fc0Weights
        Type: SPM
        Size: 192000
        Ports: 80
    - Var:
      - Name: fc0Output
        Type: SPM
        Size: 480
        Ports: 1
    - Var:
      - Name: fc0LUT
        Type: SPM
        Size: 4
        Ports: 1
  - Accelerator:
    - Name: fc1
      IrPath: benchmarks/lenet5/naive/hw/fc1.ll
      ConfigPath: benchmarks/lenet5/naive/hw/fc1.ini
      Debug: False
      PIOSize: 1
      PIOMaster: LocalBus
      Debug: False
    - Var:
      - Name: fc1Input
        Type: SPM
        Size: 480
        Ports: 120
    - Var:
      - Name: fc1Weights
        Type: SPM
        Size: 40320
        Ports: 120
    - Var:
      - Name: fc1Output
        Type: SPM
        Size: 336
        Ports: 1
    - Var:
      - Name: fc1LUT
        Type: SPM
        Size: 4
        Ports: 1