---
acc_cluster:
  - Name: lenet5
  - DMA:
    - Name: dma
      BufferSize: 128
      MaxReq: 4
      PIOMaster: LocalBus
      Type: NonCoherent
      InterruptNum: 95
  - DMA:
    - Name: StreamDma
      PIOMaster: LocalBus
      Size: 8
      Type: Stream
      ReadInt: 210
      WriteInt: 211
  - Accelerator:
    - Name: top
      IrPath: benchmarks/lenet5/shift/hw/top.ll
      ConfigPath: benchmarks/lenet5/shift/hw/top.ini
      PIOSize: 9
      PIOMaster: LocalBus
      LocalSlaves: LocalBus
      Debug: False
  - Accelerator:
    - Name: conv0
      IrPath: benchmarks/lenet5/shift/hw/conv0.ll
      ConfigPath: benchmarks/lenet5/shift/hw/conv0.ini
      Debug: False
      PIOSize: 1
      PIOMaster: LocalBus
      StreamIn: StreamDma
    - Var:
      - Name: Conv0Window
        Type: SPM
        Size: 100
        Ports: 25
    - Var:
      - Name: Conv0Weights
        Type: SPM
        Size: 600
        Ports: 25
    - Var:
      - Name: Conv0LUT
        Type: SPM
        Size: 4
        Ports: 1
    - Var:
      - Name: Conv0Out
        Type: Stream
        StreamSize: 4
        BufferSize: 16
        InCon: conv0
        OutCon: pool0
  - Accelerator:
    - Name: pool0
      IrPath: benchmarks/lenet5/shift/hw/pool0.ll
      ConfigPath: benchmarks/lenet5/shift/hw/pool0.ini
      Debug: False
      PIOSize: 1
      PIOMaster: LocalBus
    - Var:
      - Name: Pool0Window
        Type: SPM
        Size: 1344
        Ports: 4
    - Var:
      - Name: Pool0Out
        Type: Stream
        StreamSize: 4
        BufferSize: 16
        InCon: pool0
        OutCon: conv1
  - Accelerator:
    - Name: conv1
      IrPath: benchmarks/lenet5/shift/hw/conv1.ll
      ConfigPath: benchmarks/lenet5/shift/hw/conv1.ini
      Debug: False
      PIOSize: 1
      PIOMaster: LocalBus
    - Var:
      - Name: Conv1Window
        Type: SPM
        Size: 1680
        Ports: 150
    - Var:
      - Name: Conv1Weights
        Type: SPM
        Size: 9600
        Ports: 150
    - Var:
      - Name: Conv1LUT
        Type: SPM
        Size: 4
        Ports: 1
    - Var:
      - Name: Conv1Out
        Type: Stream
        StreamSize: 4
        BufferSize: 16
        InCon: conv1
        OutCon: pool1
  - Accelerator:
    - Name: pool1
      IrPath: benchmarks/lenet5/shift/hw/pool1.ll
      ConfigPath: benchmarks/lenet5/shift/hw/pool1.ini
      Debug: False
      PIOSize: 1
      PIOMaster: LocalBus
    - Var:
      - Name: Pool1Window
        Type: SPM
        Size: 3200
        Ports: 4
    - Var:
      - Name: Pool1LUT
        Type: SPM
        Size: 4
        Ports: 1
    - Var:
      - Name: Pool1Out
        Type: Stream
        StreamSize: 4
        BufferSize: 16
        InCon: pool1
        OutCon: fc0
  - Accelerator:
    - Name: fc0
      IrPath: benchmarks/lenet5/shift/hw/fc0.ll
      ConfigPath: benchmarks/lenet5/shift/hw/fc0.ini
      Debug: False
      PIOSize: 1
      PIOMaster: LocalBus
    - Var:
      - Name: fc0Window
        Type: SPM
        Size: 1600
        Ports: 80
    - Var:
      - Name: fc0Weights
        Type: SPM
        Size: 192000
        Ports: 80
    - Var:
      - Name: fc0LUT
        Type: SPM
        Size: 4
        Ports: 1
    - Var:
      - Name: fc0Output
        Type: SPM
        Size: 480
        Ports: 80
  - Accelerator:
    - Name: fc1
      IrPath: benchmarks/lenet5/shift/hw/fc1.ll
      ConfigPath: benchmarks/lenet5/shift/hw/fc1.ini
      Debug: False
      PIOSize: 1
      PIOMaster: LocalBus
      StreamOut: StreamDma
    - Var:
      - Name: fc1Window
        Type: SPM
        Size: 480
        Ports: 120
    - Var:
      - Name: fc1Weights
        Type: SPM
        Size: 40320
        Ports: 120
    - Var:
      - Name: fc1LUT
        Type: SPM
        Size: 4
        Ports: 1